name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "requirements.txt"

    - name: Pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: PyTest
      run: |
        python -m pytest

    - name: Build
      run: |
        python -m build
